### ISSUE TITLE
任务发放：实现 Graalvm Native 快捷打包的适配

### ISSUE THREAD

**Issue by noear** [noear/solon#103]
目前的思路是：借助 APT 技术，在编译时自动生成一些代码和配置。目前做这个工作插件有：

* solon.proxy.apt
* solon.graalvm.apt

可以往这个思路走。也可以用别的方案。

对于 Graalvm Native 编译来说，主要是：

* 通过配置申明资源
* 通过配置申明反射接口

**Comment by Chuanwise** [comment]
我对这一内容很感兴趣，但不知能否胜任，可以让我试试吗（OSPP）？🤔

**Comment by noear** [comment]
> 我对这一内容很感兴趣，但不知能否胜任，可以让我试试吗（OSPP）？🤔

这个已经快收尾了。

**Comment by noear** [comment]
已完工
