### ISSUE TITLE
建议优化一下文档

### ISSUE THREAD

**Issue by newhoo** [noear/solon#143]
![image](https://github.com/noear/solon/assets/22903277/6161ae66-7a61-4961-ad18-582893404523)
这代码难道不是从IDE复制出来的？

https://solon.noear.org/article/327

**Comment by newhoo** [comment]
![image](https://github.com/noear/solon/assets/22903277/e9bc0941-9dfe-4c42-a967-8965505c1c09)
![image](https://github.com/noear/solon/assets/22903277/55923cea-5bcc-4f18-bfd5-7de48a7bedf4)

**Comment by noear** [comment]
谢谢反馈：）。。。相关页面，尽快调整

**Comment by noear** [comment]
已经按你的建议，略丰富了一下。
