### ISSUE TITLE
使用 Gateway 开发 对于path参数无法获取

### ISSUE THREAD

**Issue by ppengyi** [noear/solon#162]
系统: win11
jdk: 17.0.1
相关代码
1. 定义网关
![image](https://github.com/noear/solon/assets/34240593/33a248a1-f150-48cb-832c-df939811fdb1)
2. 定一个Gateway的
![image](https://github.com/noear/solon/assets/34240593/6177631d-3891-4c10-976d-de33f2b2c189)
3. 定义一个普通的
![image](https://github.com/noear/solon/assets/34240593/2423b95a-a230-401b-9287-360363d8bd52)

输出结果
![image](https://github.com/noear/solon/assets/34240593/6475bb14-a740-4389-9a13-8f1869bd80ca)
其中path 与预期不符😊😊😊

**Comment by noear** [comment]
建议先不用 path var

**Comment by noear** [comment]
我还顺带发现另一个问题：如果请求路径，通过 ctx.pathNew() 被改了后。。。也会获取 path var 失败。

非常感谢你反馈这个问题

**Comment by noear** [comment]
已修复，会尽快发布测试版

**Comment by noear** [comment]
已修复。

**Comment by noear** [comment]
2.3.4 已发布，试下
