### ISSUE TITLE
FEATURE: 支持类似ObjectProvider多Bean注入

### ISSUE THREAD

**Issue by fuzi1996** [noear/solon#171]
`ObjectProvider`是`spring-beans`提供的一种根据泛型基类获取Bean的方式

对应全类名: `org.springframework.beans.factory.ObjectProvider`

代码位置: [ObjectProvider.java](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/ObjectProvider.java)

使用示例: 
- spring中graphql执行器配置,[GraphQlQuerydslAutoConfiguration.java](https://github.com/spring-projects/spring-boot/blob/f0e1fdfd11d651f2129023f027d92734570f842f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/data/GraphQlQuerydslAutoConfiguration.java#L53)
- mybatis-plus中自动配置,[MybatisPlusAutoConfiguration.java](https://github.com/baomidou/mybatis-plus/blob/ee231626ea1fa32d12f6616619e0d70cbd442010/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java#L134)

**Comment by fuzi1996** [comment]
@noear

**Comment by noear** [comment]
毕竟不是对等的东西。。。你讲一下直接的需求吧。。。下面这两个接口，看看是不是你想要的：

Xxx xxx = Solon.context().getBean(Xxx.class); //这个有对应的注入支持：@Inject(Xxx.class)

List<Xxx> xxxList = Solon.context().getBeansOfType(Xxx.class); //这个没有对应注入支持

**Comment by noear** [comment]
尽量是熟悉 solon 的情况下，以 solon 的风格进行适配。

**Comment by fuzi1996** [comment]
我想我已经找到解决方案了，解决方案类似`mybatis`的拓展，但是由于`GraphQL`与`GraphQLSchema`的拓展性不强,所以只能通过事件发布方式发布一些`配置bean`，通过`配置bean`收集配置信息。在`AppBeanLoadEndEvent事件`后,再构建`GraphQL`与`GraphQLSchema`

**Comment by noear** [comment]
GraphQL，怎么样啦？：）可以 pr 看看，我一起帮帮忙

**Comment by noear** [comment]
这个问题，是不是可以不需要解决了？
