### ISSUE TITLE
一个接口多个实现问题咨询

### ISSUE THREAD

**Issue by ethan-202285** [noear/solon#186]
根据debug结果，一个接口多个实现的时候，是以第一个扫描到的bean为主(org.noear.solon.core.BeanContainer#putWrap(java.lang.Class<?>, org.noear.solon.core.BeanWrap))，这个能提供配置类的吗？比如注入的是@Component index最大的bean.
还有就是这个类里，有== false的判断，这直接用!就可以了吧?

**Comment by noear** [comment]
你可以都加上名字。。。其中一个，再加 typed=true （表示，它同时以类型注册）
