### ISSUE TITLE
关于打包时出现的中文乱码问题

### ISSUE THREAD

**Issue by Ghost-HJL** [noear/solon#192]
在使用mvnd打包工具时，solon-maven-plugin打印的中文日志为?，使用mvn打包没有这个问题

[INFO] --- solon:2.4.1:repackage (default) @ xxx-xxx-xxx---
[INFO] [stdout] [info] ?????jar
[INFO] [stdout] [info] ????????xxx.xxx.xxx
[INFO] [stdout] [info] JAR??????xxx.xxx.xxx

![image](https://github.com/noear/solon/assets/55697223/7d2f0c8d-e2ef-4f48-8b91-93a1e093a4c2)

**Comment by noear** [comment]
谢谢反馈。。。下版把它改成英文的

**Comment by noear** [comment]
新的测试版本已经成英文了：2.4.4-M5 。麻烦试试

**Comment by Ghost-HJL** [comment]
好的，已经可以了，谢谢
![image](https://github.com/noear/solon/assets/55697223/beeeaa9b-ceac-4f42-ad5a-5ab7f01b4739)

**Comment by noear** [comment]
可以换成正试版了：2.4.4
