### ISSUE TITLE
Com1、Com2 为 Windows 保留文件名，使用该命名会导致 Windows 下文件不可操作

### ISSUE THREAD

**Issue by OOKAMISAMA** [noear/solon#203]
以下文件在 Windwos 中不可操作。
__test/src/main/java/webapp/demo6_aop/ioc/Com1.java
__test/src/main/java/webapp/demo6_aop/ioc/Com2.java

**Comment by noear** [comment]
dev 分支已经改掉了。

**Comment by noear** [comment]
再拉取试试。已经同步到主线了
