### ISSUE TITLE
支持使用命令行设置 构建 native image args

### ISSUE THREAD

**Issue by dudiao** [noear/solon#212]
支持：`solon.native.buildArgs`参数，比如：`mvn clean native:compile -P native -Dsolon.native.buildArgs=-march=compatibility`，该参数将会添加到`native-image.properties`中

**Comment by noear** [comment]
这个需要在 solon-maven-plugin 上调整吗？

**Comment by noear** [comment]
如果是的话。。。这个 issue 直接转到： https://github.com/noear/solon-maven-plugin

**Comment by dudiao** [comment]
@noear 两个仓库都要提交

**Comment by noear** [comment]
可以两边提交下。。。直如你所讲，这是核心模块，应该放到主仓库
