### ISSUE TITLE
org.noear.solon.net.websocket.WebSocket  无法获取唯一识别的一个key

### ISSUE THREAD

**Issue by luoren18** [noear/solon#228]
开发过程通常需要使用 key-webSocket 的形式将WebSocket对象保存在服务器，以便于主动向客户端推送数据，作者能否新增一个获取key 的方法，便于唯一识别 webSocket 对象，类似Session.getSeesionId()

<img width="661" alt="image" src="https://github.com/noear/solon/assets/19346807/2580786c-4689-49a7-b5d8-130a163ab01e">

**Comment by noear** [comment]
很好的建议。。。尽快加上：）

**Comment by noear** [comment]
不过建议使用业务性的 id 进行关联。比如 userId

**Comment by noear** [comment]
solon v2.6.1-M3 麻烦试下。。。有个：WebSocket::id 函数。（表示会话id）

**Comment by luoren18** [comment]
> solon v2.6.1-M3 麻烦试下。。。有个：WebSocket::id 函数。（表示会话id）

可以使用了

**Comment by noear** [comment]
谢谢啊！
