### ISSUE TITLE
solon-openapi2-knife4j 

### ISSUE THREAD

**Issue by xieqi520** [noear/solon#229]
solon-openapi2-knife4j 这个插件使用起来之后抱Knife4j文档请求异常

**Comment by noear** [comment]
异常，完整信息发出来看下

**Comment by xieqi520** [comment]
[Error] TypeError: undefined is not a function (near '...n.forEach...')
（匿名函数） — app.4d282859.js:1:193557
（匿名函数） — app.4d282859.js:1:191144
（匿名函数） — app.4d282859.js:1:275866

	（匿名函数） (app.4d282859.js:1:275968)
	（匿名函数） (app.4d282859.js:1:191220)
	（匿名函数） (app.4d282859.js:1:275893)

**Comment by xieqi520** [comment]
![WeChatc6d82005215c0b2a902fb6c5a0b330a2](https://github.com/noear/solon/assets/15723460/20b2499b-a250-4616-a68d-acfe958c9d08)

**Comment by noear** [comment]
还是看不出来。。。能不能写个 demo 项目，能复现问题的。。。发上来看下

**Comment by xieqi520** [comment]
![WeChatd9af75186ea64ab59e27dc20a59fce4d](https://github.com/noear/solon/assets/15723460/b9b9a168-b887-495e-9348-e57b2767d796)
就有安全验证的会出现，没有安全验证的就没有

**Comment by xieqi520** [comment]
[qingzhou-boot.zip](https://github.com/noear/solon/files/13630985/qingzhou-boot.zip)
这个开源项目加

**Comment by noear** [comment]
这个问题。后来怎么样了？

**Comment by noear** [comment]
那先关了
