### ISSUE TITLE
希望有开发修改热更新

### ISSUE THREAD

**Issue by punkwang** [noear/solon#23]
希望有开发修改热更新

**Comment by noear** [comment]
目前有热加载：）不过没有热更新的支持计划。

**Comment by noear** [comment]
现在有个用户搞的插件：solon.extend.hotdev 或许你可以试一下

**Comment by fzdwx** [comment]
我发现jrebel好像能用，热更新。简单测试

![image](https://user-images.githubusercontent.com/65269574/153751028-25cb84d9-e377-45d4-8bbc-51345ea07940.png)
![image](https://user-images.githubusercontent.com/65269574/153751036-bc064681-c101-493c-ab0e-0585e1e9ffcb.png)
---
after
![image](https://user-images.githubusercontent.com/65269574/153751065-865ab3a2-bc39-45cc-82bf-05abf3b64d1a.png)
![image](https://user-images.githubusercontent.com/65269574/153751076-fd19a3ac-6157-4c98-9aa3-8bb9bf676b22.png)

**Comment by noear** [comment]
有多个用户反馈，jrebel 可以用：）

**Comment by punkwang** [comment]
> 我发现jrebel好像能用，热更新。简单测试
> 
> ## ![image](https://user-images.githubusercontent.com/65269574/153751028-25cb84d9-e377-45d4-8bbc-51345ea07940.png)
> ![image](https://user-images.githubusercontent.com/65269574/153751036-bc064681-c101-493c-ab0e-0585e1e9ffcb.png)
> after ![image](https://user-images.githubusercontent.com/65269574/153751065-865ab3a2-bc39-45cc-82bf-05abf3b64d1a.png) ![image](https://user-images.githubusercontent.com/65269574/153751076-fd19a3ac-6157-4c98-9aa3-8bb9bf676b22.png)

可以用耶  感谢哦
