### ISSUE TITLE
jobRemove _scheduler.resumeJob?

### ISSUE THREAD

**Issue by lssmlssm** [noear/solon#237]
solon/solon-projects/solon-scheduling/solon.scheduling.quartz/src/main/java/org/noear/solon/scheduling/quartz/QuartzSchedulerProxy.java

    /**
     * 移除 job
     */
    public void remove(String name) throws SchedulerException {
        if (_scheduler != null) {
            _scheduler.resumeJob(getJobKey(name));
        }
    }

    public void pause(String name) throws SchedulerException {
        if (_scheduler != null) {
            _scheduler.pauseJob(getJobKey(name));
        }
    }

    public void resume(String name) throws SchedulerException {
        if (_scheduler != null) {
            _scheduler.resumeJob(getJobKey(name));
        }
    }

**Comment by noear** [comment]
?

**Comment by lssmlssm** [comment]
移除job remove，为什么和resume一样?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月06日 11:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [noear/solon] jobRemove _scheduler.resumeJob? (Issue #237) |

?

**Comment by noear** [comment]
@lssmlssm 这估计是个错误。你要不要提交个 pr ，把它改成 remove ？（如果没有，就不改了）
