### ISSUE TITLE
solon 的 Jredis 发布/订阅 功能失效

### ISSUE THREAD

**Issue by zengyufei** [noear/solon#241]
### 测试demo源码下载地址
https://github.com/zengyufei/solon-demo-fenci  

项目启动需要本地redis，或修改 word.local.conf 关于redis的配置

## 先上正常期望成功值，游览器 Ctrl+F 搜索到3个，正常

![正常1](https://github.com/noear/solon/assets/13251679/fed9192c-07bb-46ee-8c77-39994dc48855)
![正常2](https://github.com/noear/solon/assets/13251679/17d783b0-ccd2-40d4-b5ad-8b357294cbee)
![正常3](https://github.com/noear/solon/assets/13251679/193249d7-6461-4b5a-821b-b9932a40639e)

## 开启 solon Jredis 依赖后表现，游览器 Ctrl+F 搜索不到，排查是jredis订阅功能失效，发布正常

![失败1](https://github.com/noear/solon/assets/13251679/df75a7fa-e995-4f84-a3b6-e33645b16b38)
![失败2](https://github.com/noear/solon/assets/13251679/90469e2c-93e3-46dd-a1fa-16df2500ac7b)
![失败3](https://github.com/noear/solon/assets/13251679/c5a056f2-04c2-41c6-a78b-2efa9be00267)
![失败4](https://github.com/noear/solon/assets/13251679/87909f50-3bdd-4195-bec3-e47b791c6638)

### 测试demo源码下载地址
https://github.com/zengyufei/solon-demo-fenci

项目启动需要本地redis，或修改 word.local.conf 关于redis的配置

**Comment by noear** [comment]
谢谢反馈！

**Comment by CY-1** [comment]
我测试了 情况如下：
1. 不依赖solon.cache.jedis 依赖jedis 且jedis版本号为2.9.0      正常
2. 不依赖solon.cache.jedis 依赖jedis 且jedis版本号为5.0.2     不正常
3. 不依赖jedis 依赖solon.cache.jedis 则会引入依赖redisx:1.6.2。redisx会导致引入jedis:5.0.2    不正常

目前解决方案时修改solon-parent的pom文件redisx.version为1.4.7
       - redisx:1.5.0 会依赖jedis4.2.3
      
关于为什么redisx1.6.2不行 有待考察

**Comment by noear** [comment]
或者与 jdeis 的版本有关，我研究下 redisx 里的依赖

**Comment by noear** [comment]
我测试了一下。。。没有问题呀，都正常的。这是我的测试代码（如果同时有 jedis 依赖的话，要注意外冲突）：

```java
@Test
public void test_bus() throws Exception {
    int count = 10;
    CountDownLatch countDownLatch = new CountDownLatch(count);

    //--- bus 使用
    RedisBus bus = client.getBus();

    //发消息 （如果没有订阅者，好像消息会白发）
    Thread thread = new Thread(() -> {
        //订阅消息（这个函数会卡住线程）
        bus.subscribe((topic, message) -> {
            System.out.println(topic + " = " + message);
            countDownLatch.countDown();
        }, "topic:test");
    });

    thread.start();
    Thread.sleep(100);

    for (int i = 0; i < count; i++) {
        bus.publish("topic:test", "event-" + System.currentTimeMillis());
    }

    countDownLatch.await(2, TimeUnit.SECONDS);

    assert countDownLatch.getCount() == 0;
}
```

**Comment by CY-1** [comment]
> 4.2.3

是的 他引入的org.apdplat.word这个项目的使用的redis发布订阅功能 如果引入的jedis是5.0.2或者5.0.0都不行。4.2.3则可以。

所以具体是org.apdplat.word的兼容高版本jedis(word使用的是2.5.1)有问题 
还是说jedis的兼容问题有问题有待考察

**Comment by CY-1** [comment]
> 我测试了一下。。。没有问题呀，都正常的。这是我的测试代码（如果同时有 jedis 依赖的话，要注意外冲突）：
> 
> ```java
> @Test
> public void test_bus() throws Exception {
>     int count = 10;
>     CountDownLatch countDownLatch = new CountDownLatch(count);
> 
>     //--- bus 使用
>     RedisBus bus = client.getBus();
> 
>     //发消息 （如果没有订阅者，好像消息会白发）
>     Thread thread = new Thread(() -> {
>         //订阅消息（这个函数会卡住线程）
>         bus.subscribe((topic, message) -> {
>             System.out.println(topic + " = " + message);
>             countDownLatch.countDown();
>         }, "topic:test");
>     });
> 
>     thread.start();
>     Thread.sleep(100);
> 
>     for (int i = 0; i < count; i++) {
>         bus.publish("topic:test", "event-" + System.currentTimeMillis());
>     }
> 
>     countDownLatch.await(2, TimeUnit.SECONDS);
> 
>     assert countDownLatch.getCount() == 0;
> }
> ```

是的 如果自己测试时可以 但这个项目不行 必须要更换依赖的jedis

**Comment by noear** [comment]
这个，应该就是 版本依赖的冲突问题了。。。。A 包，依赖了 jedis a 版本；B 包，依赖了 jedis b 版本。。。当同时引入 A 和 B 包时，就冲突了（a 与 b 版本不兼容）。。。。算是特殊情况

**Comment by noear** [comment]
那我关掉了

**Comment by zengyufei** [comment]
ok，感谢两位！
