### ISSUE TITLE
官方网址无法访问，如何看文档

### ISSUE THREAD

**Issue by fzy667** [noear/solon#245]
同上

**Comment by noear** [comment]
你是说这个地址打不开？你是国内的还是国外的？哪个国家或地域？ 

https://solon.noear.org/

**Comment by fzy667** [comment]
> 你是说这个地址打不开？你是国内的还是国外的？哪个国家或地域？
> 
> https://solon.noear.org/

我国内的，我关掉魔法就可以了，因为开github所以打开了魔法，那看来可能是国外的某些区域无法访问

**Comment by fzy667** [comment]
我换了香港、湾湾节点就可以了，看来是小日子节点不行。
可以结贴了

**Comment by noear** [comment]
ok
