### ISSUE TITLE
solon 框架是否可以增加Armeria容器支持

### ISSUE THREAD

**Issue by cnrainbing** [noear/solon#248]
1. 地址：https://github.com/line/armeria
2. armeria 是Netty 作者开发的Java 服务器端容器

**Comment by noear** [comment]
这是个好主意：）

**Comment by noear** [comment]
你有没有兴趣，来适配下：）？

**Comment by cnrainbing** [comment]
> 你有没有兴趣，来适配下：）？

非常感谢 Armeria和Solon 这两个框架我还在学习中，我还得研究一下、眼前还没有这个能力，后续有机会希望我能帮上Solon开源社区

**Comment by noear** [comment]
我大致看了下 armeria ，它不算 http 容器：）。。。它应该算：应用开发框架。。。它的 http 容器用的是 jetty 的嵌入版
