### ISSUE TITLE
希望升级一下第三方库的依赖

### ISSUE THREAD

**Issue by cnrainbing** [noear/solon#252]
1. 目前很多第三方依赖包有点老了，希望及时更新一下，java 1.8 希望升级 JDK17 以上版本
2. 太老的包：okhttp、undertow、tomcat、vertx、jackson、netty、aws.s3应该使用2.x版本、grpc

**Comment by noear** [comment]
solon 是要兼容：java 1.8 到 java 22 。。。不能使用 java 17 以上的包：）

**Comment by noear** [comment]
另外 okhttp ，他们自己公司的另一个项目的最新版本也是引用 3.x 的版本！

**Comment by noear** [comment]
升级一批了，可以再检查下：）。。。不过 okhttp 还没升：）下版考虑

**Comment by cnrainbing** [comment]
感谢位社区贡献
