### ISSUE TITLE
同时有 queryString 和 from-data 参数时，Controller 方法中的参数无法正确注入

### ISSUE THREAD

**Issue by gollyhu** [noear/solon#256]
![6H9)Y_~ 23ZRH4FR55@0{5U](https://github.com/noear/solon/assets/29270714/a0159bb1-ed17-4452-aa80-82e3753f3417)

![K}O8D8{XR}X$438L2CAMBZM](https://github.com/noear/solon/assets/29270714/504ed2f5-86a2-41ab-a849-8b49f9631b2d)

smarthttp 和 jetty 的处理有此问题。。。

**Comment by noear** [comment]
收入。会尽快确认

**Comment by noear** [comment]
找到问题所在了。尽快修复：）

**Comment by noear** [comment]
帮忙试下 2.8.0-M4

**Comment by noear** [comment]
此问题已解决。了解下：

https://solon.noear.org/article/742
