### ISSUE TITLE
Solon 框架可以增加Javalin容器支持

### ISSUE THREAD

**Issue by cnrainbing** [noear/solon#258]
1. 地址：https://github.com/javalin/javalin
2. Javalin 使用起来非常简洁、很现代化

**Comment by noear** [comment]
javalin 不是容器，是开发框架。。。它内部是用 jetty 的嵌入版容器。
这个 solon 支持的：solon.boot.jetty

有空拿 javalin 实战一下，你不一定习惯的。
另外，它的并发性能也是不如 solon 的

**Comment by cnrainbing** [comment]
明白



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月18日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [noear/solon] Solon 框架可以增加Javalin容器支持 (Issue #258) |

javalin 不是容器，是开发框架。。。它内部是用 jetty 的嵌入版容器。
这个 solon 支持的：solon.boot.jetty

有空拿 javalin 实战一下，你不一定习惯的。
另外，它的并发性能也是不如 solon 的
