### ISSUE TITLE
建议Solon 未来可以支持物联网MQTT协议

### ISSUE THREAD

**Issue by cnrainbing** [noear/solon#259]
1. 现在很多互联网公司需要这种物联网业务
2. 很多做IM业务的也使用MQTT协议

**Comment by noear** [comment]
这个肯定有的：
https://solon.noear.org/article/493
https://solon.noear.org/article/family-solon-cloud-event

另外，也是可以直接使用（必须，两者没有直接耦合关系）

**Comment by cnrainbing** [comment]
收到 感谢，看了一下，好牛逼 非常易用，高级
