### ISSUE TITLE
Solon Security增加jasig.cas.client之类的sso生态

### ISSUE THREAD

**Issue by shaoerkuai** [noear/solon#288]
目前cas基本上B端项目（特别是内网IT项目）的鉴权，几乎80%以上都是CAS，10%是LDAP，剩下的就是各类自己封装的，全domain共享的jwt cookie各种牛鬼蛇神。。。

jasig cas主要是适配springboot生态，solon这块是缺失的

自己来实现的话，其实也不难，主要是调cas的接口解析xml，然后获取attributes，员工的工号，部门之类的信息。。生成本地的token，同时开一个回调接口给cas服务器，支持全站登出（可选，很多公司IT都不会默认提供这个，会有额外对接成本，懒）
但是需要自己造轮子，如果solon有这个一键接入的生态就好了。

**Comment by noear** [comment]
我对这块不熟呢。。。要不，你来提交个 pr 吧：）

**Comment by noear** [comment]
这个不需要插件适配，直接可用的：）。。。我借签网上资料写了个 demo

https://github.com/opensolon/demo_jasig-cas-client_and_solon

**Comment by noear** [comment]
后面 solon 也会推自己的 solon-auth2-server

**Comment by noear** [comment]
这倒是个主意。。。应该也可以，把 JasigCasInitializer 里的相关代码翻译成 Solon Filter

**Comment by noear** [comment]
代码可以提交到：

/opensolon/solon-integration/solon-plugin-auth/jasig-cas-solon-plugin

**Comment by noear** [comment]
有研究了吗？
