### ISSUE TITLE
关于配置文件，数组的解析

### ISSUE THREAD

**Issue by fzdwx** [noear/solon#34]
是不支持还是我写错了？这样get感觉永远取不到

![image](https://user-images.githubusercontent.com/65269574/154825992-ce3b86fa-9bc8-42fb-b5c7-99d624a85d54.png)

![image](https://user-images.githubusercontent.com/65269574/154825997-1e77aaa5-6bf2-41c3-a214-6f5a703fdb3a.png)

**Comment by noear** [comment]
看一下。。。你注入处的代码。或者到群里来

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/154828746-9bfa9a92-42a8-4983-80db-9f9bb3825bc5.png)
![image](https://user-images.githubusercontent.com/65269574/154828751-66046cb8-059d-4eab-a714-e99688f4f10d.png)
![image](https://user-images.githubusercontent.com/65269574/154828756-bb3f5fad-5fb8-4fdd-96bf-6286ac809c74.png)
![image](https://user-images.githubusercontent.com/65269574/154828759-db4f171a-4b61-4917-816f-67c7261dad3a.png)

**Comment by noear** [comment]
Solon 的配置转换实体能力比较弱。。。把 List<String> 改成 String[] 试一下

**Comment by noear** [comment]
1.6.25 版本，已增加 将配置 注入 复杂结构类的能力。。。预计明天会发布

**Comment by fzdwx** [comment]
可以😘

刘西东 ***@***.***> 于2022年2月20日周日 16:48写道：

**Comment by noear** [comment]
1.6.25 发布了。试下

**Comment by fzdwx** [comment]
好的，在搬砖，晚上回家看看🤗

刘西东 ***@***.***> 于2022年2月21日周一 11:07写道：

**Comment by noear** [comment]
最新版，现在支持任何复杂类型的结构了
