### ISSUE TITLE
Is there any way to integrate Solon RPC in an existing website

### ISSUE THREAD

**Issue by danielsawan** [noear/solon#37]
Hello,
as explained i only want to use the RPC module of Solon and integrate it into my existing website.
It is possible to do so ? If yes what should I put on the web (client) side as class to start the rpc client (replace the Client.class with what ?).

Actually i insert this line in my web controller and that don't work.

```
SolonApp client = Solon.start(Client.class, args, app -> app.enableHttp(false));
```

Thanks for your help !

**Comment by noear** [comment]
http://solon.noear.org/article/178

这里有完整rpc开发说明

**Comment by noear** [comment]
要使用 solon rpc ，需要几点要求：
1.服务端是用 solon 开发的；rpc 服务的实现用 @Remoting 注解
2.客户端是用 solon 开发的；rpc 服务的注入用 @NamiClient 注解（Nami 相当于是 Solon 的女朋友）

具体可以阅读上面的网页。

**Comment by noear** [comment]
如果想嵌到 springboot 项目里，会麻烦些。需要具体交流

**Comment by danielsawan** [comment]
Oh so if i understand your answer we can't just use the Solon RPC client in another framework ? The client need also to be a Solon client ? We can't use Solon client in Struts / Spring etc ?

**Comment by danielsawan** [comment]
even with SocketD ?

**Comment by noear** [comment]
也能在 springboot 里使用，但是会很麻烦，我没有开放这方面的资料。。。如果你使用 springboot ，建议还是使用 feign 做为客户端。

**Comment by noear** [comment]
solon rpc 是 interface 风格的，类似于 dubbo 。。。有自己的序列化要求，所以需要 solon 的服务端。

**Comment by noear** [comment]
谢谢你对 solon 项目的关注。。。可以系统的了解一下官网的内容：https://solon.noear.org

后续会推出英文版内容。

**Comment by noear** [comment]
浏览官网时，可以代用 google 浏览器的翻译进行阅读。//我是个不会英文的人

**Comment by noear** [comment]
这是配套的演示工程：[https://github.com/noear/solon-examples](https://github.com/noear/solon-examples)

**Comment by danielsawan** [comment]
我们需要这行命令来在 web 框架中启动 Salon 吗？

```
SolonApp client = Solon.start(Client.class, args, app -> app.enableHttp(false));
```

如果是，我们必须输入什么而不是 Client.class，因为 Web 框架中没有主类，只有“控制器方法”

**Comment by noear** [comment]
这是基于 tomcat 容器 + web.xml 的示例项目：

https://github.com/noear/solon-examples/tree/main/3.Solon-Web/demo3019-web_tomcat

**Comment by danielsawan** [comment]
Thank you it perfectly work !

**Comment by fzdwx** [comment]
> 浏览官网时，可以代用 google 浏览器的翻译进行阅读。//我是个不会英文的人

666
