### ISSUE TITLE
1.8.0无法启动web服务

### ISSUE THREAD

**Issue by hojit** [noear/solon#48]
机型：apple m1
1.8.0不启动web服务，1.8.1-m2正常

**Comment by noear** [comment]
如果 1.8.0 之前可以的话。。。它应该也是可以的，mvn 清除，刷新，再运行（或打包再运行）试试

**Comment by noear** [comment]
另外，欢迎加到 qq 群里交流：）

**Comment by hojit** [comment]
@noear 缓存问题，已解决
