### ISSUE TITLE
Solon 2.0 特性与需求收集

### ISSUE THREAD

**Issue by noear** [noear/solon#49]

**Comment by fzdwx** [comment]
有没有什么活，整一整 🧑🏻‍💻

**Comment by noear** [comment]
部分调整规划草案

相对明确的：

* 添加 SolonApp::context() 
* 添加 Solon.app().context(), Solon.context();
* 移除 solon.extend.sessionstate.* (已有 solon.sessionstate.*)
* 
* 更名 solon.extend.aspect          => solon.aspect          [有感]
* 更名 solon.extend.health          => solon.health          [有感]
* 更名 solon.extend.propertise.yaml => solon.config.yaml     [无感]
* 更名 solon.extend.servlet         => solon.web.servlet     [无感]
* 更名 solon.extend.staticfiles     => solon.web.staticfiles [有感]
* 更名 solon.extend.cors            => solon.web.cors        [有感]

相对不明确的：

* 移除 Aop，由 Solon.context() 替代 ?
* 更名 AopContext => AppContext ?
* solon.extend.* 全更名为：solon.* ?

**Comment by noear** [comment]
## 部分命名规范调整

### 2. 插件命名规范：(插件越来越多，怕起冲突)

* 官方适配插件命名 
  * solon-plugin-*
  * solon-cloud-plugin-*

* 第三方适配插件命名
  * *-solon-plugin
  * *-solon-cloud-plugin

### 3. 插件类包命名规范：(插件越来越多，怕起冲突)

* 容器能力对接，包名风格：
{xxx}.solon ?                      //例：cn.dev33.satoken.solon

* 接口适配对接，包名风格：
org.noear.solon.extend.{xxx} ?
org.noear.solon.cloud.extend.{xxx}  //例：org.noear.solon.cloud.extend.water
org.noear.solon.{ddd}.{xxx}         //例：org.noear.solon.cache.redis

**Comment by dyrnq** [comment]
cloud plugin support tencent polarismesh

**Comment by noear** [comment]
> cloud plugin support tencent polarismesh

收到。。。尽快安排：）

**Comment by noear** [comment]
> cloud plugin support tencent polarismesh

已添加 polaris-solon-cloud-plugin 插件。欢迎试用：http://solon.noear.org/article/401

**Comment by peigen** [comment]
是否支持树莓派（ARM 64），是否适合用GraalVM

**Comment by noear** [comment]
> 是否支持树莓派（ARM 64），是否适合用GraalVM

是否支持树莓派：这个则jdk支持的，如果有支持它的jdk就会支持。
是否适合用GraalVM：是适用的，只是比较麻烦。。。前年有用户做了个嵌入式设备类用户，就用了 Graalvm Native 打包

**Comment by noear** [comment]
> Client side load balancing with fault tolerance, support multiple protocol (HTTP, TCP, UDP).
> 
> like Netflix/ribbon and Spring Cloud LoadBalancer.

负载均衡是有的（也不限协议），可以了解一下： https://solon.noear.org/article/478

**Comment by dyrnq** [comment]
> Reference in new

谢谢，我看看

我发现一些plugin
比如 https://gitee.com/noear/solon/tree/master/_solon_plugin_cloud/zookeeper-solon-cloud-plugin  这里的
```bash
solon.cloud.zookeeper:
  server: localhost      #服务地址
```
的这里连接 zookeeper的地址是否可以传入多个server 地址然后实现client side的LB
还有
https://gitee.com/noear/solon/tree/master/_solon_plugin_cloud/nacos2-solon-cloud-plugin 这里的
```bash
solon.cloud.nacos2:
  server: localhost:8848      #服务地址
```
的server，一般这种基础中间件都是集群部署，他们或是tcp或是grcp等协议，那么就需要一个VIP来负载均衡nacos他们，假如这里可以填写多个地址的话，相当于在client side 端完成了load balancing，不知道这个想法是否可行

**Comment by noear** [comment]
中间件多server，是由中间件的客户端自己处理的。。。具体的使用，可参考官网的资料（代码仓库里不详）：

* [nacos-solon-cloud-plugin](https://solon.noear.org/article/148)
* [nacos2-solon-cloud-plugin](https://solon.noear.org/article/400)
* [zookeeper-solon-cloud-plugin](https://solon.noear.org/article/149)

**Comment by noear** [comment]
> > Reference in new
> 
> 谢谢，我看看
> 
> 我发现一些plugin 比如 https://gitee.com/noear/solon/tree/master/_solon_plugin_cloud/zookeeper-solon-cloud-plugin 这里的
> 
> ```shell
> solon.cloud.zookeeper:
>   server: localhost      #服务地址
> ```
> 
> 的这里连接 zookeeper的地址是否可以传入多个server 地址然后实现client side的LB 还有 https://gitee.com/noear/solon/tree/master/_solon_plugin_cloud/nacos2-solon-cloud-plugin 这里的
> 
> ```shell
> solon.cloud.nacos2:
>   server: localhost:8848      #服务地址
> ```
> 
> 的server，一般这种基础中间件都是集群部署，他们或是tcp或是grcp等协议，那么就需要一个VIP来负载均衡nacos他们，假如这里可以填写多个地址的话，相当于在client side 端完成了load balancing，不知道这个想法是否可行

另外，这里有 solon cloud 的完整资料：https://solon.noear.org/article/family-cloud-preview

**Comment by dyrnq** [comment]
明白了，感谢大佬回复

**Comment by noear** [comment]
有空到官网多看看，资料已经比较丰富了：https://solon.noear.org/

**Comment by dyrnq** [comment]
> 有空到官网多看看，资料已经比较丰富了：https://solon.noear.org/

嗯，必须的，向大佬学习
