### ISSUE TITLE
ServerProps 类添加一些 TCP 参数配置和线程配置？

### ISSUE THREAD

**Issue by lost22git** [noear/solon#65]
目前当 Runtime 是 Undertow 时，配置是 Undertow.Builder

当 Runtime 是 SmartHttp 时，配置是 HttpServerConfiguration

好像目前有个 ServerProps 类看起来像是我需要的，但是好像基本上 web 的配置，缺少 Tcp 参数和 io 线程的相关配置

目的：减少 app 对 runtime 的编译依赖

Jooby 也是支持多 Runtime 的，或许可以参考他的 [ServerOptions](https://github.com/jooby-project/jooby/blob/174c016cd7510c8aabbaa6b02da9a9054c40beac/jooby/src/main/java/io/jooby/ServerOptions.java)

**Comment by noear** [comment]
收到。。。后期增加一批公共配置：）

**Comment by noear** [comment]
目前发现，每个 server 对线程的配置都区别都挺大。头疼

**Comment by noear** [comment]
solon v1.10.13-M2 已实现这个需求

**Comment by noear** [comment]
配置，可以参考下这里：[http://solon.noear.org/article/174](http://solon.noear.org/article/174)
