### ISSUE TITLE
关于Solon，有没有什么能提高使用便利性的建议？欢迎你来提！

### ISSUE THREAD

**Issue by noear** [noear/solon#67]

**Comment by wxyShine** [comment]
可否用Solon 整合一套快速开发脚手架，类似若依springBoot+Vue那样的。

**Comment by noear** [comment]
> 可否用Solon 整合一套快速开发脚手架，类似若依springBoot+Vue那样的。

谢谢建议。。。已经有几个用户在开发类似的脚手架了

**Comment by guohuiyuan** [comment]
能像spring一样，加一个全局路由吗
![image](https://user-images.githubusercontent.com/54976075/203747273-88bee8dd-f877-4f31-b0e4-5d0aa4a6f30f.png)

**Comment by noear** [comment]
> spring

这个不是 “全局路由”，是上下路径啦。。。solon 不支持，不过有模拟实现的方案。可以看下：https://solon.noear.org/article/216

**Comment by noear** [comment]
> 能像spring一样，加一个全局路由吗 ![image](https://user-images.githubusercontent.com/54976075/203747273-88bee8dd-f877-4f31-b0e4-5d0aa4a6f30f.png)

后续会把目前的手动处理。下版会改成配置支持：）

**Comment by guohuiyuan** [comment]
牛的

**Comment by noear** [comment]
已增加 `server.contextPath: "/test-service/"` 配置支持
http://solon.noear.org/article/216

**Comment by sususama** [comment]
@noear Hi,有没有可以让新的贡献者做的任务吗，类似于good first issue之类的？

**Comment by noear** [comment]
> @noear Hi,有没有可以让新的贡献者做的任务吗，类似于good first issue之类的？

你好，这个怎么玩的？你有经验吗？。。。可否加到QQ群里，找我交流一下

**Comment by sususama** [comment]
我申请加群了，具体的情况我不怎么了解的，但是之前看过别的社区有good first issue之类的简单的问题可以让新手快速的入门。

**Comment by sususama** [comment]
> > @noear Hi,有没有可以让新的贡献者做的任务吗，类似于good first issue之类的？
> 
> @sususama : 你好，这个怎么玩的？你有经验吗？。。。可否加到QQ群里，找我交流一下

@noear Hi，我申请加群了，具体的情况我不怎么了解的，但是之前看过别的社区有good first issue之类的简单的问题可以让新手快速的入门。

**Comment by newhoo** [comment]
自荐一下Idea Restful插件，支持solon接口扫描、跳转、发送请求及更多实用功能。（审核中）
- https://github.com/newhoo/RestfulBox-Solon
- https://gitee.com/newhoo/RestfulBox-Solon

![plugin](https://github.com/noear/solon/assets/22903277/f642aaa5-c4e5-4160-af31-e82ca3554ce3)

**Comment by newhoo** [comment]
> 自荐一下Idea Restful插件，支持solon接口扫描、跳转、发送请求及更多实用功能。（审核中，可先本地方式安装）
> 
> * https://github.com/newhoo/RestfulBox-Solon
> * https://gitee.com/newhoo/RestfulBox-Solon
> 
> ![plugin](https://user-images.githubusercontent.com/22903277/239731861-f642aaa5-c4e5-4160-af31-e82ca3554ce3.png)

已发布 [https://plugins.jetbrains.com/plugin/21848-solon](https://plugins.jetbrains.com/plugin/21848-solon)

**Comment by dragon-dan** [comment]
使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。
按照我猜想的增加了配置项，并没有什么用。
目前处理为：
```
Solon.start(QyStartApp.class, args, (app) -> {
            // 参考org.noear.solon.cloud.CloudClient
            final String ip = app.cfg().get("solon.cloud.nacos.ip");
            final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
            app.signalAdd(new SignalSim(null, ip, port, "http", null));
        });
```
好像可以注册配置的ip了，不知道有没有更优雅的办法。

**Comment by noear** [comment]
> 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> 
> ```
> Solon.start(QyStartApp.class, args, (app) -> {
>             // 参考org.noear.solon.cloud.CloudClient
>             final String ip = app.cfg().get("solon.cloud.nacos.ip");
>             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
>             app.signalAdd(new SignalSim(null, ip, port, "http", null));
>         });
> ```
> 
> 好像可以注册配置的ip了，不知道有没有更优雅的办法。

可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174

**Comment by dragon-dan** [comment]
> > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > ```
> > Solon.start(QyStartApp.class, args, (app) -> {
> >             // 参考org.noear.solon.cloud.CloudClient
> >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> 
> 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174

文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制，
比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。
回头我改这个试下

**Comment by noear** [comment]
> > > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > > ```
> > > Solon.start(QyStartApp.class, args, (app) -> {
> > >             // 参考org.noear.solon.cloud.CloudClient
> > >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> > >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> > >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> > >         });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> > 
> > 
> > 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174
> 
> 文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制， 比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。 回头我改这个试下

这个 host 是指 ip ，例："server.host=193.10.1.3" ，但必须是本机ip

**Comment by dragon-dan** [comment]
> > > > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > > > ```
> > > > Solon.start(QyStartApp.class, args, (app) -> {
> > > >             // 参考org.noear.solon.cloud.CloudClient
> > > >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> > > >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> > > >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> > > >         });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> > > 
> > > 
> > > 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174
> > 
> > 
> > 文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制， 比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。 回头我改这个试下
> 
> 这个 host 是指 ip ，例："server.host=193.10.1.3" ，但必须是本机ip

没有限制就行，感觉可以在文档里写明有这个用法，一下就可以看到，没搞明白的估计得摸索了半天，
常用springboot的估计跟我一样第一感觉在solon.cloud.nacos下加点什么，毕竟太像了

**Comment by noear** [comment]
> > > > > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > > > > ```
> > > > > Solon.start(QyStartApp.class, args, (app) -> {
> > > > >             // 参考org.noear.solon.cloud.CloudClient
> > > > >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> > > > >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> > > > >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> > > > >         });
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> > > > 
> > > > 
> > > > 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174
> > > 
> > > 
> > > 文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制， 比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。 回头我改这个试下
> > 
> > 
> > 这个 host 是指 ip ，例："server.host=193.10.1.3" ，但必须是本机ip
> 
> 没有限制就行，感觉可以在文档里写明有这个用法，一下就可以看到，没搞明白的估计得摸索了半天， 常用springboot的估计跟我一样第一感觉在solon.cloud.nacos下加点什么，毕竟太像了

好。一次加一文。。。这个也顺带看看： https://solon.noear.org/article/412

**Comment by dragon-dan** [comment]
> > > > > > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > > > > > ```
> > > > > > Solon.start(QyStartApp.class, args, (app) -> {
> > > > > >             // 参考org.noear.solon.cloud.CloudClient
> > > > > >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> > > > > >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> > > > > >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> > > > > >         });
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> > > > > 
> > > > > 
> > > > > 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174
> > > > 
> > > > 
> > > > 文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制， 比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。 回头我改这个试下
> > > 
> > > 
> > > 这个 host 是指 ip ，例："server.host=193.10.1.3" ，但必须是本机ip
> > 
> > 
> > 没有限制就行，感觉可以在文档里写明有这个用法，一下就可以看到，没搞明白的估计得摸索了半天， 常用springboot的估计跟我一样第一感觉在solon.cloud.nacos下加点什么，毕竟太像了
> 
> 好。一次加一文。。。这个也顺带看看： https://solon.noear.org/article/412

多谢多谢，我继续探索功能去...

**Comment by noear** [comment]
> > > > > > > 使用nacos作为注册时中心自动计算的ip有问题，因为电脑上有多张物理网卡，及多张虚拟机的虚拟网卡。 按照我猜想的增加了配置项，并没有什么用。 目前处理为：
> > > > > > > ```
> > > > > > > Solon.start(QyStartApp.class, args, (app) -> {
> > > > > > >             // 参考org.noear.solon.cloud.CloudClient
> > > > > > >             final String ip = app.cfg().get("solon.cloud.nacos.ip");
> > > > > > >             final int port = Integer.parseInt(app.cfg().get("solon.cloud.nacos.port"));
> > > > > > >             app.signalAdd(new SignalSim(null, ip, port, "http", null));
> > > > > > >         });
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 好像可以注册配置的ip了，不知道有没有更优雅的办法。
> > > > > > 
> > > > > > 
> > > > > > 可以用 “server.host” 来指定当前服务的具体ip。。。详见： https://solon.noear.org/article/174
> > > > > 
> > > > > 
> > > > > 文档看过，没看配置出有这个功能，以为这个host会跟其他工具一样有限制， 比如设置了localhost，127.0.0.1和其他网卡ip就访问不了。 回头我改这个试下
> > > > 
> > > > 
> > > > 这个 host 是指 ip ，例："server.host=193.10.1.3" ，但必须是本机ip
> > > 
> > > 
> > > 没有限制就行，感觉可以在文档里写明有这个用法，一下就可以看到，没搞明白的估计得摸索了半天， 常用springboot的估计跟我一样第一感觉在solon.cloud.nacos下加点什么，毕竟太像了
> > 
> > 
> > 好。一次加一文。。。这个也顺带看看： https://solon.noear.org/article/412
> 
> 多谢多谢，我继续探索功能去...

加到 qq 群里，方便交流：）。。。仓库的 README ，或官网的技术支持里有。

**Comment by 525bigword** [comment]
最新的springboot3.1有新增一个docker-compose启动的功能，是否也能增加一个

**Comment by liyunde** [comment]
希望提供prometheus指标支持,或是支持micrometer的方法,如何获取现有指标与添加自己的指标; 不使用water这种重量级的套件;
至少监控需要兼容现有生态，才会考虑项目中采用

**Comment by noear** [comment]
> 希望提供prometheus指标支持,或是支持micrometer的方法,如何获取现有指标与添加自己的指标; 不使用water这种重量级的套件; 至少监控需要兼容现有生态，才会考虑项目中采用

目前有 opentring 的支持，或许是你需要的？可以看下：https://solon.noear.org/article/family-solon-cloud-trace

**Comment by noear** [comment]
> 希望提供prometheus指标支持,或是支持micrometer的方法,如何获取现有指标与添加自己的指标; 不使用water这种重量级的套件; 至少监控需要兼容现有生态，才会考虑项目中采用

io.micrometer 应该是可以直接使用的：）。。。另外， 有没有兴趣帮忙适配它。以增加便利度：）

**Comment by noear** [comment]
> 可否用Solon 整合一套快速开发脚手架，类似若依springBoot+Vue那样的。

@wxyShine  这个，现在有四套开源的管理后台脚手架了。你看看：

https://solon.noear.org/article/555

**Comment by kinbod** [comment]
是否能增加一个业务跟踪id的功能，给买个业务开始添加一个hash或者其他什么id直到业务执行完毕，日志都能打印出来每个业务流转过程中的ID

**Comment by noear** [comment]
@kinbod 这个早有了。而且有两个方案：）

**Comment by noear** [comment]
@kinbod 引入 solon.cloud 插件，就自带了一个轻量的了。通过 CloudClient.trace() 使用它

**Comment by kinbod** [comment]
> @kinbod 这个早有了。而且有两个方案：）

有文档说明吗？两个方案指那两个？

**Comment by noear** [comment]
@kinbod 看下官网的 学习 / [Solon Cloud 开发（分布式套件）](https://solon.noear.org/article/learn-solon-cloud)，下面有个跟踪的文

**Comment by cnrainbing** [comment]
Solon 应该专注性能和生态建设、springboot 性能是拉胯的

**Comment by noear** [comment]
@cnrainbing 你这是个好建议：）
