### ISSUE TITLE
Solon Banner plugin. Suggestions are welcome.

### ISSUE THREAD

**Issue by pmg1991** [noear/solon#77]
![image](https://user-images.githubusercontent.com/34839986/206221109-ffd0ef04-5679-4feb-97df-c2956b47ac84.png)

**Comment by pmg1991** [comment]
What is the best way to support the custom banner that any user can configure. like solon.banner.path: banner.txt?

**Comment by noear** [comment]
可以的。写个小示例方便你了解 Utils 的一些常用接口：

//通过配置获取 bannerPath
String bannerPath = Solon.cfg().get("solon.banner.path", "banner.txt");

//然后尝试获取内容
String bannerTxt = Utils.getResourceAsString(bannerPath);

//如果没有则默认为 Solon
if(Utils.isEmpty(bannerTxt)){
    bannerTxt="Solon";
}

**Comment by noear** [comment]
或许只允许使用 banner.txt 文件（基于约定大于配置的原则）：

//然后尝试获取内容
String bannerTxt = Utils.getResourceAsString("banner.txt");

//如果没有则默认为 Solon
if(Utils.isEmpty(bannerTxt)){
bannerTxt="Solon";
}

**Comment by pmg1991** [comment]
Can we make the banner the first think to print before "[Solon] App: Start loading"?

![image](https://user-images.githubusercontent.com/34839986/206391055-630c8672-240e-4e6c-be7b-bd2945470d16.png)

**Comment by noear** [comment]
如果那样的话，需要加到 solon 内核项目：solon 。。。这样，会让它的包变大的：）。。。先保持现在这样吧：）

可以提交 pr 了。。。用 dev 开发，pr 到 dev 啊：）

**Comment by noear** [comment]
我还想在 solon 2.0 时，把 solon 内核模埠，降到 200k 以下的：）

**Comment by pmg1991** [comment]
Please review
