### ISSUE TITLE
任务发放：适配 graphql ：graphql-solon-plugin

### ISSUE THREAD

**Issue by noear** [noear/solon#90]
效果类似 “graphql-spring-boot-starter”

**Comment by StringKe** [comment]
在支持标准 GraphqQL 的时候，建议同时支持 subscription 可以使用 SSE 方式。

**Comment by fuzi1996** [comment]
认领

**Comment by fuzi1996** [comment]
@noear https://github.com/noear/solon/pull/176 先不要合并,只是为了让你看看，我打算昨晚batchloader和订阅再一起合并

**Comment by noear** [comment]
@fuzi1996 好的！

**Comment by StringKe** [comment]
@noear 不是规范之一，是客户端单向订阅的一种选择。

**Comment by fuzi1996** [comment]
@noear 目前的实现有个问题，只能对`Conmponent`注解的类的方法进行拦截，无法对`Controller`中方法进行拦截，无法复用`Controller`中的逻辑。有什么好办法吗？

**Comment by noear** [comment]
拦截？是可以的

**Comment by noear** [comment]
你想不加注解，就拦截？还是加注解进行拦截？

**Comment by noear** [comment]
不管怎么样，Controller 都是可以拦截的。。。

**Comment by noear** [comment]
你对Conmponent注解的类的，是怎么拦截的。。。放点代码，我看下，然后给你份 controller 拦截的示意代码

**Comment by fuzi1996** [comment]
> 你对Conmponent注解的类的，是怎么拦截的。。。放点代码，我看下，然后给你份 controller 拦截的示意代码

https://github.com/fuzi1996/solon/blob/222794a52179e54e5c444ae0bb6272ea7e821676/solon-projects/solon-plugin/graphql-solon-plugin/src/main/java/org/noear/solon/extend/graphql/GraphqlPlugin.java#L42-L49C19

通过 [提取 Bean 的函数进行定制开发](https://solon.noear.org/article/36) 实现

如果使用aop，性能会不会有问题

在spring中只要是在bean中使用Graphql的注解都会生效

**Comment by noear** [comment]
原来在这里留的言，我还找了半天：）。。。要不这样，你先只支持 Commpent 注解好了。。。你提交后，我再看看，调整下。

**Comment by noear** [comment]
你先只支持 `@Component` 注解吧。。。你提交后，我再看看，如果有必要再调整。

**Comment by fuzi1996** [comment]
已完成初步适配

- 添加`query`与`Mutation` https://github.com/noear/solon/pull/176
- 添加`batchLoader` https://github.com/noear/solon/pull/201
- 添加`Subscription` https://github.com/noear/solon-integration/pull/2

**Comment by fuzi1996** [comment]
@noear 目前graphql使用还有一个问题，就是只能对`Component`进行aop,无法对`Controller`,详见: https://github.com/noear/solon/issues/90#issuecomment-1651825157

**Comment by noear** [comment]
> @noear 目前graphql使用还有一个问题，就是只能对`Component`进行aop,无法对`Controller`,详见: [#90 (comment)](https://github.com/noear/solon/issues/90#issuecomment-1651825157)

@fuzi1996 我大概知道原因了。。。你是拿它当组件用是吧？当组件用时，它没有aop功能。。。mvc 用时，会转成 action 此时才会有 aop 功能

**Comment by noear** [comment]
已完成。2.8.2
