### ISSUE TITLE
任务发放：实现 sprinb boot admin 类似的工具

### ISSUE THREAD

**Issue by noear** [noear/solon#96]
实现 “spring-boot-admin-starter-server” + “spring-boot-admin-starter-client” 的效果。方便为小项目提供监控面板

**Comment by shaokeyibb** [comment]
Please assign this task to me, thx.

**Comment by noear** [comment]
已发布为：开源之夏的项目

**Comment by noear** [comment]
已基本完成：https://solon.noear.org/article/580
